spring.application.name=invoicekit
#spring.datasource.url=jdbc:postgresql://localhost:5432/invoicekit_db
#spring.datasource.username=postgres
#spring.datasource.password=root

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#server.port=8080
server.port=${PORT:8080}
spring.mail.host=smtp.gmail.com
#spring.mail.port=587
spring.mail.port=465
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.auth=true

spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000

gmail.client.id=${GMAIL_CLIENT_ID}
gmail.client.secret=${GMAIL_CLIENT_SECRET}
gmail.refresh.token=${GMAIL_REFRESH_TOKEN}
gmail.sender.email=${GMAIL_SENDER_EMAIL}

spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

#spring.mail.properties.mail.smtp.starttls.enable=true

management.endpoints.web.exposure.include=health
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1

jwt.secret=${JWT_SECRET}

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_OAUTH_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_OAUTH_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile

# GitHub OAuth2
spring.security.oauth2.client.registration.github.client-id=${GITHUB_OAUTH_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_OAUTH_CLIENT_SECRET}
spring.security.oauth2.client.registration.github.scope=user:email
